#+title: A Static-Site Generator for Cicognara's Catalgo

* Background
Since 2015 or so, the Princeton University Library has collaborated with a consortium of libraries and research institutions, with funding from the Kress Foundation, on a project called the [[https://cicognara.org/][Digital Cicognara Library]].  Labeled "an open-acess collection of the early literature of the arts," this project combines two distinct efforts: (1) to create a union catalog of copies and similiar editions of some 5,000 imprints collected by Count Leopoldo Cicognara (1767–1834) and itemized in his /Catalogo ragionato dei libri d’arte e d’antichità/; (2) to build a web resource that enables users to read and compare digital facsimiles of many of these imprints.  Cicognara's original library now resides in the Vatican; in the 1980s, the Kress Foundation sponsored a project to create a microfiche edition of the entire library (more than one million pages).

Many of the original imprints have since been deemed too fragile to be handled, so a similar edition of digital images cannot be made.  In lieu of such a digital edition, several research institutions are examining their holdings for copies, or similar editions, of Cicognara's volumes.  The collaborating institutions are digitizing what they find and making their digital editions available, via the Web, in a digital recreation of Cicognara's library.  The discovery, comparison, and description of these copies constitutes a significant bibliographic research project in its own right.

Dissemination of this digital recreation has been the responsibility of PUL, which has built and maintains a collection of bespoke software to harvest bibliographic records and IIIF manifests from the collaborators, process and index them, and display them in a web browser.  The software provides some search capabilities, along with a way to browse the collection through a TEI-encoded edition of Cicognara's /Catalogo/.

The software behind the Digital Cicognara Library is showing its age, and PUL no longer supports bespoke digital library applications.  Furthermore, the aims and rationales for the system have changed over the years, as have the relationships among and commitments of the institutional partners.  The Kress Foundation has provided PUL with an eighteen-month grant to sunset the Cicognara application and migrate as much of its functionality as possible to other, sustainable platforms.
