#+title: A Static-Site Generator for Cicognara's Catalgo

* Background
Since 2015 or so, the Princeton University Library has collaborated with a consortium of libraries and research institutions, with funding from the Kress Foundation, on a project called the [[https://cicognara.org/][Digital Cicognara Library]].  Labeled "an open-acess collection of the early literature of the arts," this project combines two distinct efforts: (1) to create a union catalog of copies and similiar editions of some 5,000 imprints collected by Count Leopoldo Cicognara (1767–1834) and itemized in his /Catalogo ragionato dei libri d’arte e d’antichità/; (2) to build a web resource that enables users to read and compare digital facsimiles of many of these imprints.  Cicognara's original library now resides in the Vatican; in the 1980s, the Kress Foundation sponsored a project to create a microfiche edition of the entire library (more than one million pages).

Many of the original imprints have since been deemed too fragile to be handled, so a similar edition of digital images cannot be made.  In lieu of such a digital edition, several research institutions are examining their holdings for copies, or similar editions, of Cicognara's volumes.  The collaborating institutions are digitizing what they find and making their digital editions available, via the Web, in a digital recreation of Cicognara's library.  The discovery, comparison, and description of these copies constitutes a significant bibliographic research project in its own right.  All the partner institutions send their metadata (MARC records; IIIF manifests) to the Getty, which disseminates them via a portal (whose existence makes much of the Digital Cicognara Library site functionally redundant).

In 2016 or so, the Kress Foundation digitized its microfiche edition; in addition to its other digitized holdings, PUL maintains these in its digital repository.

Dissemination of these materials has been the responsibility of PUL, which has built and maintains a system of bespoke software to harvest bibliographic records and IIIF manifests from the Getty, process and index them, and display them in a web browser.  The software provides some search capabilities, along with a way to browse the collection through a TEI-encoded edition of Cicognara's /Catalogo/.

The software behind the Digital Cicognara Library is showing its age, and PUL no longer supports bespoke digital library applications.  Furthermore, the aims and rationales for the system have changed over the years, as have the relationships among and commitments of the institutional partners.  The Kress Foundation has provided PUL with an eighteen-month grant to sunset the Cicognara application and migrate as much of its functionality as possible to other, sustainable platforms.

* The Digital Cicognara Library Today
The present project attempts to fulfill these goals, first by analyzing the Digital Cicognara Library as it is today.  The name, /the Digital Cicognara Library/, is misleading; it implies that the subject so named is a virtual collection, or a virtual space, that replicates or simulates Count Cicognara's original library.  While this is partially true, we have seen that DCL is actually an organization: consortium of research institutions engaged in several distinct, though related, activities:

1. *Compiling a Union Catalog.* This was the earliest activity of the consortium.  It is the work of trained bibliographers, not technologists, and it is painstaking, scholarly work, largely unfunded.  These endeavors have yielded a few surprises, including the complex bibliographic nature of some of Cicognara's holdings.  Before the project began, it was assumed that most, if not all, of Cicognara's volumes were, while old, not particularly rare, and that duplicates or similar editions could be found in the partners' holdings.  Close examination of the /Catalogo/ revealed that some of Cicognara's volumes were idiosyncratic /Sammelbände/ for which no duplicates existed.  The complexities of early modern publishing also made it difficult to impossible to determine how closely an edition held by a partner institution corresponded with Cicognaro's copy.

2. *Creating Digital Editions.* At the outset, the partner institutions were made responsible for digitizing their holdings: for creating and curating high-quality digital images, and for writing IIIF manifests that could be used to display the digital editions with any capable IIIF viewer, and for maintaining a IIIF image server for delivering the images.  In practice, a number of the partners have been unable to fulfill one or more of these responsibilities.

3. *Providing a Digital Reading Interface.* PUL has been responsible for designing, building, and maintaining the software that drives the CDL website.  That software, [[https://github.com/pulibrary/cicognara-rails][cicognara-rails]], is a web application, written using the Ruby on Rails framework, that bundles a number of distinction functionalities:

   - /it harvests the CDL's metadata from the Getty Portal./ This metadata includes MARC records and IIIF manifests from all the partners; it must be filtered, modified, and matched with the App's internal data structures.  The process is complex; it has not worked for several years.

   - /it indexes the metadata for search, discovery, and cross-linking./  The cicognara-rails app has no database; all of its data-related functionality relies on separate Solr application, whose deployment must be carefully maintained and whose complex configurations must be updated whenever new functionality is added.

   - /it serves web pages./ The user-visible aspect of the CDL is the Rails application itself.  It has a RESTful API with two endpoints: [[https://cicognara.org/catalog][https://cicognara.org/catalog]], a standard digital-library catalog interface with searching and faceting; and [[https://cicognara.org/catalogo][https://cicognara.org/catalogo]], an HTML rendition of the TEI-encoded /Catalogo/ with links to catalog entries.  The URLs for entries (e.g., [[https://cicognara.org/catalog/1122][https://cicognara.org/catalog/1122]]) resolve to pages that include a list of items matching the catalog item (the digitized microfiche; one or more digitized editions of copies from partner institutions) and a Javascript viewer widget (the [[https://universalviewer.io/][UniversalViewer]]) that renders the IIIF manifest.

* Desiderata
At the highest level, the /desideratum/ is to retire the current cicognaro-rails app so that PUL's development team is no longer responsible for maintaining a rickety, out-of-date Rails application.  Beyond this organizational imperative, however, PUL's obligations are unclear.  At the very least, the Kress Foundation has asked that the digitization of its microfiche collection be made available, and it is to address this requirement that this small project is proposed.
